name: setup-mkosi
description: Install mkosi and all its dependencies

runs:
  using: composite
  steps:

  - name: Permit unprivileged access to kvm, vhost-vsock and vhost-net devices
    shell: bash
    run: |
      sudo adduser $(id -un) kvm
      sudo sed -i '/kvm/s/0660/0666/g'   /usr/lib/tmpfiles.d/static-nodes-permissions.conf
      sudo sed -i '/vhost/s/0660/0666/g' /usr/lib/tmpfiles.d/static-nodes-permissions.conf
      sudo modprobe kvm
      sudo modprobe vhost_vsock
      sudo modprobe vhost_net
      [[ -e /dev/kvm ]] && sudo chmod 666 /dev/kvm
      sudo chmod 666 /dev/vhost-vsock
      sudo chmod 666 /dev/vhost-net
      lsmod
      [[ -e /dev/kvm ]] && ls -l /dev/kvm
      ls -l /dev/vhost-*

  - name: Dependencies
    shell: bash
    run: ${{ github.action_path }}/tools/install-dependencies.sh

  - name: Update systemd
    shell: bash
    working-directory: ${{ github.action_path }}
    run: ${{ github.action_path }}/tools/update-systemd.sh

  - name: Install
    shell: bash
    run: sudo python3 -m pip install ${{ github.action_path }}
